export const TELEMETRY_EVENTS = {
  accountDeleted: 'account_deleted',
  accountExported: 'account_exported',
  apiRequestFailed: 'api_request_failed',
  auditSaved: 'audit_saved',
  authSignInFailed: 'auth_sign_in_failed',
  authSignInStarted: 'auth_sign_in_started',
  authSignOutFailed: 'auth_sign_out_failed',
  authSignOutSucceeded: 'auth_sign_out_succeeded',
  aiPromptCopied: 'ai_prompt_copied',
  checklistCreated: 'checklist_created',
  checklistDeleted: 'checklist_deleted',
  checklistShared: 'checklist_shared',
  checklistUnshared: 'checklist_unshared',
  checklistUpdated: 'checklist_updated',
  copyActionCompleted: 'copy_action_completed',
  ctaClicked: 'cta_clicked',
  externalCtaClicked: 'external_cta_clicked',
  filterChanged: 'filter_changed',
  mcpSetupClicked: 'mcp_setup_clicked',
  mcpToolCalled: 'mcp_tool_called',
  mcpRuleRequested: 'mcp_rule_requested',
  mcpRuleReturned: 'mcp_rule_returned',
  profileGithubSynced: 'profile_github_synced',
  profileUpdated: 'profile_updated',
  progressBulkSynced: 'progress_bulk_synced',
  ruleCompleted: 'rule_completed',
  ruleFeedbackSubmitted: 'rule_feedback_submitted',
  ruleNotesUpdated: 'rule_notes_updated',
  ruleUncompleted: 'rule_uncompleted',
  searchOpened: 'search_opened',
  shareActionClicked: 'share_action_clicked',
  waitlistJoined: 'waitlist_joined'
} as const

export type TelemetryEventName = (typeof TELEMETRY_EVENTS)[keyof typeof TELEMETRY_EVENTS]
